server:
  port: 8080
spring:
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: standbyScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
logging:
  config: classpath:log/logback.xml
mybatis:
  mapper-locations: classpath:mapper/lotteryTicket.xml
druid:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://119.3.0.12:3306/lotteryticket?useUnicode=true&characterEncoding=utf8
  username: root
  password: lvyl1234
  type: com.alibaba.druid.pool.DruidDataSource